spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8001